# Generated by Django 4.2.13 on 2024-05-24 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_user_email_ci_uniqueness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
