# Generated by Django 4.2.13 on 2024-05-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_keyword_keyword_menu_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='Alert',
        ),
    ]
