# Generated by Django 4.2.13 on 2024-06-04 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_keyword_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('yahentamitsi_dining_hall', models.BooleanField(default=False)),
                ('south_dining_hall', models.BooleanField(default=False)),
                ('two_fifty_one_dining_hall', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.menu')),
            ],
        ),
    ]
