# Generated by Django 4.2.13 on 2024-06-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_dailymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
