# Generated by Django 4.2.13 on 2024-06-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_email_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_is_verified',
        ),
    ]
