# Generated by Django 4.2.13 on 2024-06-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_email_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_email_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
