# Generated by Django 4.2.13 on 2025-01-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_phone_profile_receive_email_alerts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyMenu',
            new_name='DailyMenuItem',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='UniqueMenuItem',
        ),
        migrations.RenameField(
            model_name='uniquemenuitem',
            old_name='item',
            new_name='name',
        ),
    ]
