# Generated by Django 4.2.13 on 2025-01-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_dailymenu_dailymenuitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='dailymenuitem',
            old_name='south_dining_hall',
            new_name='dh_251',
        ),
        migrations.RenameField(
            model_name='dailymenuitem',
            old_name='two_fifty_one_dining_hall',
            new_name='dh_south',
        ),
        migrations.RenameField(
            model_name='dailymenuitem',
            old_name='yahentamitsi_dining_hall',
            new_name='dh_y',
        ),
        migrations.AddField(
            model_name='uniquemenuitem',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniquemenuitem',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniquemenuitem',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniquemenuitem',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniquemenuitem',
            name='serving_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MenuItemAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.allergen')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.uniquemenuitem')),
            ],
        ),
    ]
