# Generated by Django 4.2.13 on 2025-01-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_dailymenu_dailymenuitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymenuitem',
            old_name='south_dining_hall',
            new_name='dh_251',
        ),
        migrations.RenameField(
            model_name='dailymenuitem',
            old_name='two_fifty_one_dining_hall',
            new_name='dh_south',
        ),
        migrations.RenameField(
            model_name='dailymenuitem',
            old_name='yahentamitsi_dining_hall',
            new_name='dh_y',
        ),
    ]
