# Generated by Django 4.2.13 on 2025-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_allergen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquemenuitem',
            name='ingredients',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
