# Generated by Django 4.2.13 on 2025-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_allergen_uniquemenuitem_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquemenuitem',
            name='serving_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
