# Generated by Django 5.0.4 on 2024-05-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_remove_keyword_user_keyword_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='user_id',
            new_name='user',
        ),
    ]
