# Generated by Django 5.0.4 on 2024-05-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='username',
        ),
    ]
